spring:
  application:
    name: qr-menu-web
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session
    timeout: 1800
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 5MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    secret:
      key: ${JWT_SECRET_KEY}
    token:
      access:
        expiration: 900000
      refresh:
        expiration: 604800000
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}

server:
  port: 8080
  ssl:
    enabled: false

s3:
  bucket-name: ${S3_BUCKET_NAME}
  placeholder-thumbnail: ${PLACEHOLDER_THUMBNAIL}

resend:
  api:
    key: ${RESEND_API_KEY}

app:
  base-url: ${BASE_URL}
  frontend-url: ${FRONTEND_URL}
  menu:
    base-domain: ${MENU_BASE_DOMAIN}
    worker-queue: queue:worker
  security:
    reset-token-expiry-minutes: 30
  mail:
    from: "QRMenu <no-reply@menu.furkancavdar.com>"
